### PR TITLE
add openstatus

### PR DESCRIPTION
**Pull request by thibaultleouay**

### CODE REVIEW

**Comment by ivbeg** [comment]
Please avoid any marketing words like "beautiful".

**Comment by sjackson0109** [comment]
Errr..doesn’t this very repo include such a word ‘awesome’?On 16 Aug 2023, at 16:46, Ivan Begtin ***@***.***> wrote:﻿
Please avoid any marketing words like "beautiful".

**Comment by thibaultleouay** [comment]
@ivbeg  sure but what about 
```
* [Pulsetic](https://pulsetic.com/) - create beautiful status pages & incident management reports and keep your visitors updated
```

**Comment by ivbeg** [comment]
@thibaultleouay thanks. I will clean up that word too.

**Pull request merged**
